### ISSUE TITLE
invalid response hostname '', while expecting 'example.domain.com'

### ISSUE THREAD

**Issue by montanaflynn** [ezzarghili/recaptcha-go#33]
We're using recaptcha v2 checkbox and have "Verify the origin of reCAPTCHA solutions" turned on:

<img width="627" alt="Screen Shot 2020-08-08 at 12 25 42" src="https://user-images.githubusercontent.com/24260/89703166-5263e900-d972-11ea-9551-62ee2566a7ab.png">

We're also checking the hostname in Go:

```go
options := recaptcha.VerifyOption{}
options.Hostname = "example.domain.com"
```

For most verifications it's working but we do see a fair number of these errors:

`invalid response hostname '', while expecting 'example.domain.com'`

This is a bit odd to me since it looks like it's happening to normal users on our website. Any idea why this could happen?

**Comment by ezzarghili** [comment]
Normally you would need to use the Hostname verification only when you have the "Verify the origin.." option disabled otherwise they are taking care of that verification.

Also I am not sure about the reliability of the the hostname check from google (I've seen reports before that they sometimes return empty strings).

A case I still did not verify is installed WPA, will they still provide the hostname or a `ApkPackageName`.

**Comment by montanaflynn** [comment]
Since it's the first check here I wonder if they don't send hostnames when there's some error condition. 

https://github.com/ezzarghili/recaptcha-go/blob/master/recaptcha.go#L145-L191

I'm going to log the full response and see exactly what google is sending and if there's some pattern.

**Comment by ezzarghili** [comment]
Thanks, That would be very helpful, I don't currently have any production project running the library.

**Comment by montanaflynn** [comment]
As suspected the response does not always contain hostname, for example:

```json
{
  "success": false,
  "error-codes": [
    "timeout-or-duplicate"
  ]
}
```

So basically I think the change should be to move the hostname check to the very end of the logic here:

https://github.com/ezzarghili/recaptcha-go/blob/master/recaptcha.go#L126-L193
